### ISSUE TITLE
部署calico-01时弹窗出错

### ISSUE THREAD

**Issue by planktonzp** [shenshouer/calico-kubernetes#2]
`==> calico-01: chmod: cannot access '/srv/kubernetes/*': No such file or directory`
`The SSH command responded with a non-zero exit status. Vagrant`
`assumes that this means the command failed. The output for this command`
`should be in the log above. Please read the output to determine what`
`went wrong.`
同时停止部署 不知道是哪里的错误 我的系统参数
`Linux Dipper 4.5.1-1-ARCH #1 SMP PREEMPT Thu Apr 14 19:19:32 CEST 2016 x86_64 GNU/Linux`
如果需要其他信息我再回复您 谢谢

**Comment by shenshouer** [comment]
我这个是基于coreos的，要不你在coreos上试试？

**Comment by planktonzp** [comment]
这个错已经解决了 从 git上拉下来最新版本的K8S和calico手动编译就能行 但导入配置生成的虚拟机内不知为何不生成对应的hosts文件

**Comment by planktonzp** [comment]
roy@Dipper ~/Git/coreos (git)-[master] % vagrant ssh calico-01
Last login: Thu Apr 21 01:36:16 2016 from 10.0.2.2
CoreOS alpha (1010.1.0)
Update Strategy: No Reboots
core@calico-01 ~ $ kubectl get node
NAME            STATUS    AGE
172.18.18.101   Ready     1d
172.18.18.102   Ready     1d
172.18.18.103   Ready     1d
core@calico-01 ~ $ kubectl create -f skydns.yaml
namespace "kube-system" created
service "kube-dns" created
replicationcontroller "kube-dns-v9" created
core@calico-01 ~ $ kubectl create -f kube-ui-rc.yaml
replicationcontroller "kube-ui-v5" created
core@calico-01 ~ $ kubectl create -f kube-ui-svc.yaml
service "kube-ui" created
core@calico-01 ~ $ kubectl get po -o wide --namespace=kube-system
NAME                READY     STATUS              RESTARTS   AGE       NODE
kube-dns-v9-3nez0   0/4       ContainerCreating   0          51s       172.18.18.103
kube-ui-v5-gdyu6    1/1       Running             0          35s       172.18.18.101
core@calico-01 ~ $ kubectl create -f busybox.yaml
pod "busybox" created
core@calico-01 ~ $ kubectl get po -o wide --namespace=kube-system
NAME                READY     STATUS              RESTARTS   AGE       NODE
kube-dns-v9-3nez0   0/4       ContainerCreating   0          2m        172.18.18.103
kube-ui-v5-gdyu6    1/1       Running             0          1m        172.18.18.101
core@calico-01 ~ $ kubectl get po -o wide
NAME      READY     STATUS    RESTARTS   AGE       NODE
busybox   1/1       Running   0          17s       172.18.18.102
输出的文件很多地方不一样啊 没有labels 而且经常性不稳定

**Comment by shenshouer** [comment]
可能是版本不同的原因，你可以`kubectl version`看下具体版本，然后使用最新版的kubernetes二进制文件替换重启vagrant即可，不稳定可能是calico插件比较消耗资源或者虚拟机性能问题

**Comment by shenshouer** [comment]
出现找不到/srv/kubernetes/*目录可以在key.sh里面修改:

```
mkdir -p /opt/bin/ && mkdir -p /srv/kubernetes/ && mkdir -p /opt/kubernetes/manifests/ && cd /opt/bin/ && cp -rf /vagrant/cloud-config/* ./ && chmod a+x * 
mkdir -p /opt/cni/bin && cd /opt/cni/bin && mv /opt/bin/calico ./ && mv /opt/bin/calico-ipam ./

/opt/bin/make-ca-cert.sh 172.18.18.101 IP:172.18.18.101,IP:10.100.0.1,DNS:kubernetes,DNS:kubernetes.default,DNS:kubernetes.default.svc,DNS:kubernetes.default.svc.cluster.local
chmod 664 /srv/kubernetes/*

# CGO_ENABLED=0 go install -v -a -tags netgo -installsuffix netgo -ldflags "-w -X github.com/docker/swarm/version.GITCOMMIT `git rev-parse --short HEAD` -X github.com/docker/swarm/version.BUILDTIME \"`date -u`\""

```

**Comment by planktonzp** [comment]
搞定了 谢谢 部署成功 有后续不懂的还得麻烦你 新入门的菜鸟 多多包涵

**Comment by shenshouer** [comment]
没事，我也是在学习，以后咱们多交流
